### ISSUE TITLE
Why `no-cache`?

### ISSUE THREAD

**Issue by kayx23** [ealmansi/graphqlzero#101]
Testing graphql caching in the downstream and found `cache-control: no-store` header in the response. 

What was the consideration of not allowing caching for the queries and mutations?

https://github.com/ealmansi/graphqlzero/blob/f577a1838f0c4e61096ca22968dab5c62f8a6066/apps/graphqlzero-web/pages/index.tsx#L581-L588

**Comment by ealmansi** [comment]
hi @kayx23,

on the topic of caching, from the [Apollo Server docs](https://www.apollographql.com/docs/apollo-server/api/plugin/cache-control/):
> by default, no operation results are cached unless you set cache hints

since this is a reference/educational project, keeping default behaviours is likely the best way to avoid confusion for beginners

as a side note: the code you linked is client code from the website itself; it does not prescribe the server's caching behaviour. aka: `fetchPolicy: "no-cache"` is not related to the API response containing the `cache-control: no-store` response

**Comment by kayx23** [comment]
This is clear. Thanks!
